MyDeployProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from MyDeployProject import settings

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('article.urls', namespace='main')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.conf.urls import url
from article.views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^articles/$', articles, name='articles'),
    url(r'^articles/page/(\d+)/$', articles, name='articles_page'),
    url(r'^article/(?P<art_id>\d+)/$', article, name='article'),

]

article/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Article(models.Model):
    class Meta():
        """описывает название таблицы"""
        db_table = "article"

    article_title = models.CharField(max_length=200)
    article_text = RichTextUploadingField()
    article_date = models.DateTimeField()

    def __str__(self):
        """Возвращает строковое представление модели, а именно название статьи"""
        return 'Article %d: %s' % (self.id, self.article_title)


class Comments(models.Model):
    class Meta():
        db_table = 'comments'

    comments_text = models.TextField()
    comments_article = models.ForeignKey(Article)


class Mainpage(models.Model):
    """Данная модель отвечает за главную страницу блога"""

    class Meta:
        db_table = 'mainpage'

    page_title = models.CharField(max_length=200)
    start_text = RichTextUploadingField()

    def __str__(self):
        return 'Main page'

article/views.py
from django.contrib import auth
from django.core.paginator import Paginator
from django.shortcuts import render_to_response, get_object_or_404
from article.models import Article, Mainpage


#My Views
def index(request):
    """Основная страница"""
    args = {}
    args['mainpage'] = get_object_or_404(Mainpage, id=1)
    return render_to_response('index.html', args)

def articles(request, page_number=1):
    """Список всех статей"""
    all_articles = Article.objects.all()
    current_page = Paginator(all_articles, 2)
    return render_to_response('articles.html', {'articles':current_page.page(page_number),
                                                'username':auth.get_user(request).username,
                                                }
                              )

def article(request, art_id=1):
    """Выбранная статья"""
    args = {}
    args['article'] = get_object_or_404(Article, id=art_id)
    return render_to_response('article.html', args)

article/templates/article.html
{% extends 'main.html' %}
{% load staticfiles %}



{% block title %}{{ article.article_title }}{% endblock title %}

{% block content %}

    <div class="container" style="padding: 20px">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h5>Дата публикации: {{ article.article_date }}</h5>
                <h3>{{ article.article_title }}</h3>
            </div>
            <div class="panel-body">
                {% autoescape off %}{{ article.article_text }}{% endautoescape %}
            </div>
        </div>
        <div>
            <a href="{% url 'main:articles' %}" class="btn btn-info" role="button" data-toggle="tooltip" title="Назад" data-placement="right"><img src="{% static 'back.gif' %}"></a>
        </div>

    </div>

    <!-- Это код позволяет отображать подсказки при наведении курсора -->
    <script>
        $(document).ready (function (){
            $('[data-toggle="tooltip"]').tooltip ();
        });
    </script>

{% endblock content %}

article/templates/articles.html
{% extends 'main.html' %}


{% block title %}Articles{% endblock %}

{% block content %}

<div class="container" style="padding: 20px">
    {% for article in articles %}
        <div class="panel panel-primary">
            <div class="panel-body">
                <h6>Дата публикации: {{ article.article_date }}</h6>
                <h3><a href="{% url 'main:article' article.id %}">{{ article.article_title }}</a></h3>
            </div>
        </div>
    {% endfor %}

{#    Пагинация#}
    <nav>
        <div class="large-3 large-centered columns">
            <ul class="pagination">
                {% if articles.has_previous %}
                    <li class="arrow-only"><a href="{% url 'main:articles_page' articles.previous_page_number %}">&laquo;</a></li>
                {% endif %}
                {% for page in articles.paginator.page_range %}
                    {% if page == articles.number %}
                        <li class="current"><a href="{% url 'main:articles_page' page %}">{{ page }}</a></li>
                    {% else %}
                        <li><a href="{% url 'main:articles_page' page %}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if articles.has_next %}
                    <li class="arrow-only"><a href="{% url 'main:articles_page' articles.next_page_number %}">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

{% endblock %}

article/templates/index.html
{% extends 'main.html' %}


{% block title %}{{ mainpage.page_title }}{% endblock %}
{% block content %}
    <div class="container">
        {% autoescape off %}{{ mainpage.start_text }}{% endautoescape %}
    </div>
{% endblock %}

templates/main.html
{% load bootstrap3 %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">  <!-- для адаптации в смартфонах -->

    <title>Blog ItWin || {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}">

    <!-- подключение bootstrap -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% static "style.css" %}

</head>

<body style="background: #eeeeee">

<div class="navbar navbar-default navbar-fixed-top" style="background-color: #689ecc; border-color: #181dae">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'main:index' %}">Logo Company</a>
            <a class="navbar-brand" href="{% url 'main:articles' %}">My topics</a>
            <a class="navbar-brand" href="admin/">Admin Panel</a>
        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    {#выпадающее меню#}
                    <div class="dropdown">
                        <button class="btn btn-info dropdown-toggle"
                                data-toggle="dropdown" style="margin: 8px;">Usefull sources<span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header" style="color: #c7254e">Разработка</li>
                            <li><a href="https://github.com/">GitHub</a></li>
                            <li><a href="https://hub.docker.com/">Docker Hub</a></li>
                            <li><a href="https://travis-ci.org/">Travis CI</a></li>
                            <li><a href="https://bettercodehub.com/">Better Code Hub</a></li>
                            <li><a href="https://aws.amazon.com/ru/">Amazon Web Services</a></li>
                            <li><a href="https://www.heroku.com/">Heroku</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header" style="color: #c7254e">Обсуждение</li>
                            <li><a href="https://habrahabr.ru/">Хабрахабр</a></li>
                            <li><a href="https://toster.ru/">Тостер</a></li>
                            <li><a href="https://stackoverflow.com/">Stack Overflow</a></li>
                        </ul>
                    </div>
                    {#конец выпадающему меню#}
                </li>
            </ul>

            {#            панель авторизации#}
            {#            <form class="navbar-form navbar-right">#}
            {#                <div class="form-group">#}
            {#                    <input type="text" placeholder="Email" class="form-control">#}
            {#                </div>#}
            {#                <div class="form-group">#}
            {#                    <input type="password" placeholder="password" class="form-control">#}
            {#                </div>#}
            {#                <button type="submit" class="btn btn-success">Go</button>#}
            {#            </form>#}
        </div>
    </div>
</div>

<div class="jumbotron">
    <div style="padding: 2%">
        {% block content %} {% endblock %}
    </div>
</div>


<div class="container" style="position: fixed; bottom: 20px;">
    <p>&copy; Все права защищены 2017</p>
    <img src='https://bettercodehub.com/edge/badge/ARTobstrel/MyDeployProject?branch=master'>
</div>


<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

</body>
</html>